server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kimmingyu0/spring-cloud-config-demo
          search-paths: spring-cloud-config-file/**
          default-label: main
